# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- master
- DEPLOY/*
- deploy/*

# Don't run against PRs
pr: none

variables:
- name: APP_NAME
  value: go-docker-k8s-demo
- group: Container Journey
- group: 'CI Variables'

stages:
- stage: build
  jobs:
  - job: "run_build_push_acr"
    pool:
      vmImage: 'Ubuntu 16.04'
    variables:
      GOBIN:  '$(GOPATH)/bin' # Go binaries path
      GOROOT: '/usr/local/go1.11' # Go installation path
      GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
      modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code
    steps:
    - script: |
        mkdir -p '$(GOBIN)'
        mkdir -p '$(GOPATH)/pkg'
        mkdir -p '$(modulePath)'
        shopt -s extglob
        shopt -s dotglob
        mv !(gopath) '$(modulePath)'
        echo '##vso[task.prependpath]$(GOBIN)'
        echo '##vso[task.prependpath]$(GOROOT)/bin'
      displayName: 'Set up the Go workspace'
    
    - script: |
        mkdir -p '$(GOBIN)'
        mkdir -p '$(GOPATH)/pkg'
        mkdir -p '$(modulePath)'
        shopt -s extglob
        shopt -s dotglob
        mv !(gopath) '$(modulePath)'
        echo '##vso[task.prependpath]$(GOBIN)'
        echo '##vso[task.prependpath]$(GOROOT)/bin'
      displayName: 'Set up the Go workspace'

    - script: |
        # Login to Azure 
        echo "az login --service-principal --username $(SP_APP_ID) --password $(SP_PASS) --tenant $(SP_TENANT)"
        az login --service-principal --username "$(SP_APP_ID)" --password "$(SP_PASS)" --tenant "$(SP_TENANT)"
      workingDirectory: '$(modulePath)'
      displayName: 'Azure Login'

    - script: |
        # go version
        # # Login to Azure 
        # echo "az login --service-principal --username $(SP_APP_ID) --password $(SP_PASS) --tenant $(SP_TENANT)"
        # az login --service-principal --username "$(SP_APP_ID)" --password "$(SP_PASS)" --tenant "$(SP_TENANT)"
        # Use ACR build task to build and push
        echo "az acr build -r $(ACR_NAME) --image $(Build.Repository.Name):$(build.BuildNumber) ."
        az acr build -r $(ACR_NAME) --image $(Build.Repository.Name):$(build.BuildNumber) .
      workingDirectory: '$(modulePath)'
      displayName: 'ACR Build and Publish'

    - script: |
        pwd
      displayName: 'print dir'
      workingDirectory: '$(modulePath)'

    - task: Docker@2
      inputs:
        containerRegistry: 'hellorings_acr'
        repository: 'spartan-app'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(Build.Repository.Name):$(build.BuildNumber)'
      
    - bash: |
        curl $SCRIPT > script.sh
        chmod +x ./script.sh
        tag_name="$(Build.Repository.Name):$(build.BuildNumber)"
        commitId=$(Build.SourceVersion)
        commitId=$(echo "${commitId:0:7}")
        echo "./script.sh $(ACCOUNT_NAME) $(ACCOUNT_KEY) $(TABLE_NAME) $(PARTITION_KEY) p1 $(Build.BuildId) imageTag $tag_name commitId $commitId service $(Build.Repository.Name)"
        ./script.sh $(ACCOUNT_NAME) $(ACCOUNT_KEY) $(TABLE_NAME) $(PARTITION_KEY) p1 $(Build.BuildId) imageTag $tag_name commitId $commitId service $(Build.Repository.Name)
      displayName: Update manifest pipeline details in CJ db
      env:
        SCRIPT: https://raw.githubusercontent.com/samiyaakhtar/spk/686-simply-pipelines/scripts/update_introspection.sh
    
    - script: |
        echo "some data for the file" >> $(System.DefaultWorkingDirectory)/my_artifact.txt
      displayName: 'Write out file'
      
    - task: PublishPipelineArtifact@1
      inputs:
        path: $(System.DefaultWorkingDirectory)/my_artifact.txt
        artifact: my_artifact

- stage: hld_update
  dependsOn: build
  condition: and(succeeded('build'), or(startsWith(variables['Build.SourceBranch'], 'refs/heads/DEPLOY/'),eq(variables['Build.SourceBranchName'],'master')))
  jobs:
  - job: update_image_tag
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - script: |
        function get_fab_version() {
            if [ -z "$VERSION" ]
            then
                VERSIONS=$(curl -s https://api.github.com/repos/Microsoft/fabrikate/tags)
                LATEST_RELEASE=$(echo $VERSIONS | grep "name" | head -1)
                VERSION_TO_DOWNLOAD=`echo "$LATEST_RELEASE" | cut -d'"' -f 4`
            else
                echo "Fabrikate Version: $VERSION"
                VERSION_TO_DOWNLOAD=$VERSION
            fi
        }

        # Obtain OS to download the appropriate version of Fabrikate
        function get_os() {
            if [[ "$OSTYPE" == "linux-gnu" ]]; then
                eval "$1='linux'"
            elif [[ "$OSTYPE" == "darwin"* ]]; then
                eval "$1='darwin'"
            elif [[ "$OSTYPE" == "msys" ]]; then
                eval "$1='windows'"
            else
                eval "$1='linux'"
            fi
        }    

        # Download Fabrikate
        function download_fab() {
            echo "DOWNLOADING FABRIKATE"
            echo "Latest Fabrikate Version: $VERSION_TO_DOWNLOAD"
            os=''
            get_os os
            fab_wget=$(wget -SO- "https://github.com/Microsoft/fabrikate/releases/download/$VERSION_TO_DOWNLOAD/fab-v$VERSION_TO_DOWNLOAD-$os-amd64.zip" 2>&1 | egrep -i "302")
            if [[ $fab_wget == *"302 Found"* ]]; then
              echo "Fabrikate $VERSION_TO_DOWNLOAD downloaded successfully."
            else
                echo "There was an error when downloading Fabrikate. Please check version number and try again."
            fi
            wget "https://github.com/Microsoft/fabrikate/releases/download/$VERSION_TO_DOWNLOAD/fab-v$VERSION_TO_DOWNLOAD-$os-amd64.zip"
            unzip fab-v$VERSION_TO_DOWNLOAD-$os-amd64.zip -d fab
        }

        # Install Fabrikate
        function install_fab() {
            # Run this command to make script exit on any failure
            set -e
            export PATH=$PATH:$HOME/fab
            fab install
            echo "FAB INSTALL COMPLETED"
        }


        echo "RUN HELM INIT"
        helm init
        get_fab_version
        download_fab
        ls -la
        #install_fab
      displayName: 'Download Fabrikate'
    - script: |
        function git_connect() {
        pwd
            git clone https://automated:$(GITHUB_TOKEN)@github.com/edaena/fabrikate-spartan-cluster.git

            cd fabrikate-spartan-cluster
        }
        pwd
        git_connect
        git checkout -b "DEPLOY/$(Build.BuildNumber)"
        ../fab/fab set --subcomponent $(Build.Repository.Name) image.tag=$(Build.BuildNumber)

        echo "GIT STATUS"
        git status
        echo "GIT ADD (git add -A)"
        git add -A

        #Set git identity 
        git config user.email "admin@azuredevops.com"
        git config user.name "Automated Account"

        echo "GIT COMMIT"
        git commit -m "Updating image tag to $(Build.BuildNumber) for common environment"

        echo "GIT PUSH"
        git push https://$(GITHUB_TOKEN)@github.com/edaena/fabrikate-spartan-cluster.git

        latest_commit=$(git rev-parse --short HEAD)
        echo "latest_commit=$latest_commit"

        # Download update storage script
        curl https://raw.githubusercontent.com/samiyaakhtar/spk/686-simply-pipelines/scripts/update_introspection.sh > script.sh
        chmod +x script.sh
        ./script.sh $(ACCOUNT_NAME) $(ACCOUNT_KEY) $(TABLE_NAME) $(PARTITION_KEY) imageTag "$(Build.Repository.Name):$(build.BuildNumber)" p2 $(Build.BuildId) hldCommitId $latest_commit env "DEV"
      env:
        GITHUB_TOKEN_VAR: $(GITHUB_TOKEN)



